import pandas as pd
from faker import Faker
import random
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--start_id', type=int, default=1, help='Starting ID for the records')
parser.add_argument('--num_records', type=int, default=10000, help='Number of records to generate')

args = parser.parse_args()

# Initialize Faker
fake = Faker()

# Define the parameters
num_records = args.num_records # Number of posts
start_id = args.start_id

# Define possible platforms and categories
platforms = ['Twitter', 'Instagram', 'Facebook', 'LinkedIn']
categories = ['Groceries', 'Electronics', 'Clothing', 'Dining', 'Entertainment', 'Travel', 'Health', 'Education']

# Define category-based content and sentiment mapping
category_data = {
    'Groceries': {
        'positive': [
            "Bought fresh organic vegetables today!", "Discounts available on dairy products.",
            "Exploring new gluten-free items at the store.", "Tried a new vegan snack, loved it!",
            "Stocked up on pantry essentials for the month.", "Fresh fruits are in season, love it!",
            "Found amazing deals on organic grains.", "Cooking healthy meals with fresh produce.",
            "Loving the variety of vegan options available.", "Discovered delicious homemade sauces.",
            "Bought locally sourced fresh herbs.", "Excited about new healthy recipes.",
            "Trying out new healthy snacks.", "Great deals on plant-based products.",
            "Stocking up for a week of nutritious meals.", "Discovered high-quality organic spices.",
            "Excited about the new range of gluten-free bread.", "Fresh milk supply was perfect this time.",
            "Bought farm-fresh eggs at a great price.", "Delighted to find new dairy alternatives.",
            "Avocados were perfectly ripe and delicious!", "Exploring fermented foods for gut health.",
            "Excited about trying out fresh sourdough bread.", "Stocked up on healthy fermented drinks.",
            "Exploring different varieties of whole grains.", "Happy with the quality of fresh seafood.",
            "Discovered amazing probiotic drinks.", "Healthy food choices are easier now.",
            "Stocked up on natural sweeteners.", "Happy to see locally sourced organic produce.",
            "Fresh salads taste even better with organic cucumbers.", "Found a variety of protein bars.",
            "Organic mushrooms added a great flavor.", "The new almond milk tastes so creamy!",
            "Stocked up on antioxidant-rich berries.", "Fresh ginger and turmeric for immunity boost.",
            "Love the freshness of the herbs I bought.", "My pantry is full of healthy options.",
            "Happy with the variety of vegan alternatives.", "Bought delicious sugar-free dark chocolate.",
            "New probiotic yogurt tastes fantastic.", "Exploring natural herbs for immunity boost.",
            "Fresh coconut water is my go-to drink.", "Loaded up on superfoods for my smoothies.",
            "Discovered amazing natural peanut butter.", "Love the freshness of the almond flour.",
            "New gluten-free wraps are so tasty.", "Found a great variety of organic juices.",
            "Enjoying fresh citrus fruits this season.", "Healthy choices make me feel better.",
            "Delighted with the variety of dairy-free cheeses.", "Fresh herbs add so much flavor.",
            "Found affordable organic quinoa.", "Stocked up on premium quality olive oil.",
            "Love the aroma of fresh herbs and spices.", "Discovered new detox drinks.",
            "Healthy snacking just got easier!", "Fresh basil added flavor to my dishes.",
            "Found an amazing range of protein powders.", "Loaded up on immunity-boosting foods.",
            "Freshly squeezed juices taste divine.", "Discovered sugar-free almond cookies.",
            "Excited to try organic buckwheat flour.", "Loving the fresh cold-pressed juices.",
            "Stocked up on low-carb snacks.", "Perfectly ripe bananas for smoothies.",
            "Great discounts on healthy breakfast cereals.", "Tried gluten-free pancakes, loved them!",
            "My salads taste better with fresh avocados.", "Fresh berries make my breakfast healthy.",
            "Happy with the freshness of the dairy.", "Organic lentils make cooking nutritious.",
            "Discovered new plant-based protein options.", "Healthy eating just got easier.",
            "Excited about gluten-free baking options.", "Found zero-preservative packaged juices.",
            "Fresh spinach and kale for smoothies.", "Loaded up on high-fiber foods.",
            "Excited to try a new vegan cheese.", "Great variety of healthy snack bars.",
            "Found cold-pressed coconut oil at a discount.", "Stocked up on almond flour for baking.",
            "Healthy breakfast just got more exciting.", "Discovered sugar-free breakfast cereals.",
            "Happy to find natural nut butters.", "Fresh garlic and ginger add magic to cooking.",
            "Stocked up on wholesome lentil pasta.", "Found an amazing variety of probiotics.",
            "Happy with the variety of sugar-free desserts.", "My smoothie game just leveled up.",
            "Excited to explore new fermented foods.", "Loaded up on wholesome healthy grains.",
            "Great quality of fresh organic eggs.", "Delighted to find organic turmeric powder.",
            "Healthy spreads make my breakfast better.", "Found an amazing selection of herbal teas.",
            "Stocked up on my favorite granola.", "Loving the fresh almond milk for coffee.",
            "Fresh herbs make my recipes flavorful.", "Found healthy snack options for kids.",
            "Excited about the organic baking supplies.", "Loaded up on fiber-rich whole grains.",
            "Happy to find zero-sugar coconut water.", "Discovered a variety of keto snacks.",
            "Excited about the new fermented beverages.", "My pantry is packed with healthy options.",
            "Delighted with the freshness of fruits.", "Healthy eating is fun with these choices.",
            "Stocked up on wholesome snacks.", "Loaded up on antioxidant-rich foods.",
            "Discovered an amazing variety of dry fruits.", "Fresh lemons enhance my detox drinks.",
            "Loving the fresh variety of seasonal fruits.", "Delighted to try natural almond butter.",
            "Excited about trying homemade kombucha.", "My grocery haul looks super healthy.",
            "Fresh produce makes meal prep easier.", "Excited about discovering nutritious snacks.",
            "Loving the range of fermented vegetables.", "Stocked up on cold-pressed oils.",
            "Healthy foods keep my family energized.", "Fresh juices made my breakfast perfect.",
            "Delighted to try organic fruit preserves.", "Stocked up on my favorite nut milk.",
            "My pantry looks colorful and healthy.", "Excited to try fermented probiotic drinks.",
            "Loaded up on protein-packed superfoods.", "Fresh herbs add magic to my dishes.",
            "Healthy eating is now so much easier!", "Excited about homemade almond milk."
        ],

        'neutral': [
            "Visited the grocery store today.", "Checked out the new organic section.",
            "Explored some new brands of dairy products.", "Compared prices of gluten-free items.",
            "Read reviews on different pantry essentials.", "Made a list of groceries to buy this week.",
            "Noticed some new arrivals in the fresh produce section.", "Browsing through seasonal fruit options.",
            "Looked into healthier snack alternatives.", "Trying to decide between almond and soy milk.",
            "Added a few vegan products to my cart.", "Evaluated different types of bread for nutrition.",
            "Checked the expiry dates on dairy products.", "Scanned the ingredients of packaged juices.",
            "Exploring options for homemade sauces.", "Thought about trying some probiotic drinks.",
            "Examined the freshness of vegetables before buying.", "Visited the frozen foods aisle for quick meals.",
            "Saw some interesting offers on cereals.", "Compared nutritional values of breakfast options.",
            "Looked at new varieties of nuts and seeds.", "Checked for seasonal discounts on groceries.",
            "Reviewed the packaging of organic products.", "Browsing through different types of cooking oils.",
            "Compared plant-based milks for taste.", "Examined the sugar content in granola bars.",
            "Explored fermented food options for gut health.", "Looked for gluten-free alternatives to regular pasta.",
            "Thought about adding healthy spreads to my diet.", "Looked at the calorie content of my favorite snacks.",
            "Exploring herbal tea options for relaxation.", "Evaluated the quality of fresh herbs in store.",
            "Checked out cold-pressed juices in the fridge.", "Visited the grocery store to compare prices.",
            "Examined the quality of packaged lentils.", "Evaluated different brands of olive oil.",
            "Looked for deals on low-sodium soups.", "Exploring options for organic grains.",
            "Compared different types of sweeteners.", "Checked for additives in processed snacks.",
            "Browsing through the health food section.", "Compared sugar levels in flavored yogurt.",
            "Examined fresh fish for quality.", "Looked at vegan cheese options.",
            "Reviewed available probiotic drinks.", "Compared packaging quality of pantry staples.",
            "Explored local brands of fermented pickles.", "Checked shelf life of perishable items.",
            "Looked into cold-pressed oils for cooking.", "Compared price differences in organic produce.",
            "Thought about switching to homemade granola.", "Visited the bakery section to explore new options."
        ],

        'negative': [
            "Disappointed with the quality of vegetables this time.", "Fruits were overripe and spoiled quickly.",
            "The organic produce had a lot of dirt, difficult to clean.", "Bought bread that went stale the next day.",
            "Found bugs in the grains I purchased.", "The dairy products expired before the mentioned date.",
            "Vegetables wilted after just one day.", "Too many preservatives in packaged snacks.",
            "The fruits looked fresh but tasted bland.", "Price for organic items is too high.",
            "The store was out of fresh herbs again.", "Received damaged packaging on pantry essentials.",
            "Frozen items thawed too quickly during delivery.", "Expired products still on the shelves.",
            "Quality of pulses has gone down recently.", "The nuts tasted stale and lacked crunch.",
            "The gluten-free bread was dry and tasteless.", "Too much sugar in supposedly healthy snacks.",
            "Dairy alternatives had a weird aftertaste.", "Found mold on the organic cheese I bought.",
            "Organic vegetables were smaller and less fresh.", "Packaged juices tasted artificial.",
            "Milk carton was leaking when delivered.", "Fruit packaging was torn and leaking.",
            "The bakery section smelled stale.", "Packaged salads had wilted leaves inside.",
            "Honey had crystallized and was unusable.", "The cereals tasted stale after opening.",
            "Too much salt in the packaged soups.", "Found dirt in the fresh spinach bundle.",
            "Healthy snacks were overpriced and bland.", "The oil had a strange odor and taste.",
            "Low-carb products lacked freshness.", "Avocados were either under-ripe or overripe.",
            "Yogurt had separated and smelled off.", "Frozen fruits were covered in ice crystals.",
            "Vegetables had pesticides despite being organic.", "Delivery was delayed, and produce wilted.",
            "Bought expired almond milk by mistake.", "Probiotic drinks tasted overly sour.",
            "Canned items had dents, unsafe to use.", "Pre-cut fruits went bad faster than expected.",
            "Found insects in the packaged lentils.", "The organic chicken had a strange smell.",
            "Pantry essentials had inconsistent quality.", "Received the wrong order for my groceries.",
            "Healthy spreads had an unusual texture.", "Too much artificial flavor in juices.",
            "Almond butter was too oily and separated.", "The packaging of grains was torn.",
            "The granola bars were too hard to bite.", "Dairy-free cheese did not melt properly.",
            "Natural sweeteners tasted artificial.", "Packaged hummus was sour and spoiled.",
            "Mold formed on bread even before the expiry date.", "Cold-pressed juices had an off-taste.",
            "Poor quality herbs with dry leaves.", "The probiotic drink was flat and flavorless.",
            "Berries had mold despite being freshly packed.", "Natural peanut butter was overly salty.",
            "Fermented drinks had leaked in the packaging.", "Received wrong flavors in my yogurt order.",
            "The fresh fish had a bad smell.", "Nuts tasted rancid despite being sealed.",
            "Frozen vegetables were watery after cooking.", "Seeds were stale and had no crunch.",
            "The fruit preserves had sugar crystals inside.", "Herbal tea packets smelled musty.",
            "New brand of coconut oil was too watery.", "Delivery left my groceries in the sun.",
            "Sugar-free cookies tasted like cardboard.", "The granola was too sweet for a healthy option.",
            "Probiotic yogurt had an unpleasant smell.", "Cold-pressed oils had particles inside.",
            "Expired canned goods delivered without checking.", "Frozen meat had freezer burns.",
            "Found stones in the packet of lentils.", "Low-sodium soups were bland and watery.",
            "Disappointed with the bland taste of new spreads.", "Too many additives in sugar-free snacks.",
            "Bottled coconut water tasted sour.", "Received rotten eggs in the delivery.",
            "Muesli had a strong stale smell.", "Almond flour was clumpy and unusable.",
            "Fresh herbs had a lot of dirt.", "The baby spinach had yellowed leaves.",
            "The vegan butter was greasy and flavorless.", "Organic chickpeas had a chemical smell.",
            "The salad dressing was too vinegary.", "Unsweetened almond milk tasted bitter.",
            "Too many preservatives in natural juices.", "Healthy chips lacked flavor and crunch.",
            "Frozen berries had freezer burns.", "Homemade kombucha was overly fermented.",
            "The spice blends had a musty smell.", "Fermented pickles tasted overly salty.",
            "Cold-pressed ginger shots were too spicy.", "Received leaking containers of yogurt.",
            "Found spoiled mangoes in the fresh produce.", "Healthy smoothies had an odd aftertaste.",
            "Vegan mayo was too oily and bland.", "Herbal detox tea tasted bitter and unpleasant."
        ]

    },
    'Electronics': {
        'positive': [
            "Just bought the latest smartphone, it's amazing!", "Loving the performance of my new laptop.",
            "Great deals on smart home devices this season.", "Upgraded to a 4K TV, the picture quality is fantastic!",
            "Installed a smart security system, feeling secure.", "Exploring new features on my smartwatch.",
            "Got a new tablet, perfect for reading and browsing.", "Upgraded my gaming console, the experience is top-notch!",
            "Discovered a great noise-canceling headset.", "Loving the clarity of my new wireless earbuds.",
            "My new wireless mouse works flawlessly.", "Great battery life on my new phone, lasting all day!",
            "Tried out the latest Bluetooth speaker, loving it!", "Bought a smart home hub, everything's connected now.",
            "My new monitor has excellent resolution for work.", "Happy with my smart thermostat, saving energy!",
            "Amazing performance from my new graphics card.", "Bought a portable charger, super useful while traveling.",
            "Set up a smart light system, ambiance is perfect.", "My new camera captures stunning photos.",
            "The latest smart TV is a game-changer for movies.", "Bought a robot vacuum, keeping the house spotless!",
            "Loving the sound quality of my home theater system.", "Installed a smart doorbell, works perfectly!",
            "Great experience with my new digital assistant.", "Bought a Wi-Fi extender, no more dead zones!",
            "My new gaming headset is super comfortable.", "My wireless charger is so convenient, love it!",
            "Enjoying seamless connectivity with my smart speaker.", "Upgraded to a fast SSD, system runs so smoothly.",
            "Bought a new fitness tracker, tracking goals easily.", "Impressed with the clarity of my new webcam.",
            "Upgraded my router, internet speed has improved.", "Smart home automation is making life so easy.",
            "Loving the new features on my upgraded smartwatch.", "My new power bank is super reliable for trips.",
            "Tested my VR headset, the experience is incredible.", "Upgraded my tablet, enjoying the improved battery.",
            "Bought a digital photo frame, loving the slideshow.", "Loving the upgraded interface of my smart TV.",
            "The new smart plug works perfectly with my devices.", "Enjoying seamless gaming with my upgraded GPU.",
            "My new electric toothbrush is super efficient.", "Bought a new DSLR, the image quality is amazing!",
            "Smart home devices have made life so convenient.", "My new wireless keyboard is smooth and responsive.",
            "Tested my new projector, movies look so immersive!", "Fast-charging my devices with the new adapter.",
            "Impressed with the security features of my router.", "Got a smart lock, enhancing my home's security.",
            "Loving the quick responsiveness of my smart TV.", "Bought a new Bluetooth keyboard, typing is smooth.",
            "My smart scale helps me track fitness goals easily.", "Upgraded my earbuds, the sound is crystal clear.",
            "The wireless connectivity of my new printer is flawless.", "My e-reader makes reading so enjoyable!",
            "New smart bulbs make my home look amazing.", "Using my new tablet for work has boosted productivity.",
            "Upgraded my PC, multitasking is seamless now.", "Loving the advanced AI features on my phone.",
            "New noise-canceling headphones are a game-changer.", "Bought a smart oven, cooking has never been easier.",
            "My new smartwatch helps me stay on track.", "Upgraded my graphics card, gaming feels more real.",
            "Smart thermostat helps me save on energy bills.", "Exploring fun features on my VR headset!",
            "New portable speakers deliver impressive sound.", "My new fitness band helps me stay active.",
            "Great experience with my upgraded home theater.", "Bought a fast external SSD, saving time on backups.",
            "Smart assistant integration makes life so easy.", "Loving the extended battery life on my new phone.",
            "Bought a home automation system, very impressed.", "My upgraded webcam is perfect for video calls.",
            "Great storage capacity on my new external drive.", "Smart air purifier keeps my room fresh and clean.",
            "Upgraded my e-reader, reading is more fun now!", "New gaming laptop handles all games smoothly.",
            "Fast and reliable Wi-Fi after upgrading my router.", "My smart fitness scale tracks progress perfectly.",
            "The upgraded VR experience is mind-blowing.", "Bought a powerful graphics tablet for designing.",
            "My new action camera records stunning videos.", "Great user experience with my new smart fridge."
        ],

        'neutral': [
            "Checked out the specs of the latest smartphone.", "Reading reviews for the newest laptop models.",
            "Considering upgrading to a 4K TV soon.", "Exploring options for smart home devices.",
            "Looking at different brands of noise-canceling headphones.", "Researching smartwatches with fitness tracking.",
            "Comparing various smart security systems.", "Exploring tablet options for work and leisure.",
            "Went through reviews of gaming consoles.", "Learning about the latest VR headset technology.",
            "Considering getting a smart assistant for my home.", "Checked out the features of a new fitness tracker.",
            "Exploring the pros and cons of different routers.", "Reading up on the benefits of smart home hubs.",
            "Considering options for a digital photo frame.", "Checking battery life specs for different smartphones.",
            "Exploring options for upgrading to a gaming laptop.", "Reading reviews on new Bluetooth speakers.",
            "Considering getting a smart plug to control appliances.", "Looking into different brands of projectors.",
            "Learning about the latest Wi-Fi extender options.", "Reading about the advantages of smart locks.",
            "Exploring options for upgrading my monitor.", "Checking compatibility for smart home devices.",
            "Considering getting a new electric toothbrush.", "Reading about advancements in DSLR technology.",
            "Exploring different portable charger options.", "Comparing features of smart light bulbs.",
            "Looking at deals on high-capacity external drives.", "Reading about benefits of smart thermostats.",
            "Checking user feedback on wireless keyboards.", "Considering options for upgrading my router.",
            "Learning about the features of modern smart TVs.", "Exploring options for wireless charging pads.",
            "Comparing different brands of action cameras.", "Looking into smart air purifiers for my home.",
            "Reading about the latest advancements in VR.", "Exploring the pros and cons of smart ovens.",
            "Considering upgrading to a better home theater system.", "Researching available graphics cards for gaming.",
            "Comparing different e-reader models.", "Looking into budget-friendly webcam options.",
            "Reading about the durability of noise-canceling earbuds.", "Checking out new power bank designs.",
            "Exploring options for a faster external SSD.", "Considering switching to a smart lock system.",
            "Learning about new firmware updates for smart home devices.", "Comparing storage capacities of USB drives.",
            "Researching compatibility of smart assistant devices.", "Looking into voice-controlled smart devices.",
            "Exploring the latest AI features in modern smartphones.", "Checking reviews of new digital assistant models."
        ],
        'negative': [
            "My new laptop is overheating constantly.", "Disappointed with the battery life of the smartphone.",
            "The smart TV lags while streaming content.", "Headphones stopped working after a week.",
            "Issues with connecting my Bluetooth speaker.", "The smartwatch fails to sync with my phone.",
            "My new gaming console crashes frequently.", "The smart home assistant is unresponsive.",
            "Charging takes too long for the power bank.", "Touch screen on my tablet is not responsive.",
            "VR headset causes motion sickness.", "Disappointed with the audio quality of my earbuds.",
            "The router keeps dropping the connection.", "Battery life of the fitness tracker is disappointing.",
            "Frequent disconnections with wireless keyboard.", "My external hard drive stopped working suddenly.",
            "Wi-Fi extender does not cover enough range.", "Smart light bulbs are difficult to configure.",
            "Action camera battery drains too quickly.", "Smart lock fails to recognize voice commands.",
            "Projector quality is poor in daylight.", "Slow response from my smart thermostat.",
            "Difficult to update firmware on my smart devices.", "Smartwatch display has dead pixels.",
            "Delay in notifications from my smart assistant.", "The monitor shows flickering randomly.",
            "Noise-canceling headphones aren't effective.", "Smart plug randomly disconnects from Wi-Fi.",
            "Digital photo frame is not user-friendly.", "Smart oven takes too long to heat up.",
            "Struggled to set up my smart home hub.", "Mic on the wireless headset stopped working.",
            "Power bank heats up during charging.", "Voice assistant gives inaccurate responses.",
            "The portable charger stopped working unexpectedly.", "Issues with pairing my Bluetooth keyboard.",
            "Air purifier makes too much noise.", "Graphics card performance is underwhelming.",
            "My smart lock battery drains too fast.", "Camera lens fails to focus properly.",
            "Difficult to reset the smart home hub.", "Projector overheats after prolonged use.",
            "Smart speaker randomly restarts.", "Fitness tracker miscounts steps frequently.",
            "Smart light turns off without any command.", "USB drive is not compatible with my system.",
            "Digital assistant fails to answer basic queries.", "Disappointed with the build quality of my tablet.",
            "Wi-Fi extender is inconsistent.", "The smart plug loses connection frequently.",
            "Smartwatch struggles with notifications.", "Bluetooth connectivity is unstable.",
            "External SSD is slower than expected.", "Projector image quality is poor at night.",
            "Camera app crashes when recording video.", "Smart air purifier emits strange noises.",
            "Thermostat settings reset on their own.", "VR headset is uncomfortable to wear.",
            "Smart lock struggles with voice recognition.", "Wireless earbuds disconnect during calls.",
            "Smart assistant has difficulty understanding commands.", "Router frequently needs to be reset.",
            "E-reader display freezes occasionally.", "Webcam quality is blurry in low light.",
            "Battery backup for my gaming console is poor.", "Graphics card overheats under load.",
            "Charging dock is incompatible with my device.", "Smart home system crashes during updates.",
            "Tablet screen brightness fluctuates randomly.", "Smart device setup instructions are unclear."
        ]

    },
    'Clothing':{
        'positive': [
            "Absolutely love the quality of the fabric!", "The new summer collection is stunning!",
            "The dress fits perfectly and feels comfortable.", "Thrilled with the vibrant colors of the outfits.",
            "The jacket is super warm and stylish.", "Received many compliments on my new outfit.",
            "Great discounts on trendy apparel this season.", "The t-shirts are soft and feel amazing!",
            "Loving the new designs in the winter collection.", "Just bought a cozy sweater, so comfy!",
            "Impressed by the durability of the jeans.", "The new formal wear fits like a dream.",
            "Great quality for the price!", "The stitching is top-notch and durable.", 
            "The dress looks exactly like the picture.", "The size chart was accurate and helpful.",
            "Fabric feels soft on the skin, perfect for summer.", "Stylish and comfortable at the same time!",
            "The colors did not fade even after multiple washes.", "Perfect fitting, love the slim cut!",
            "Happy with the variety of options available.", "Bought matching outfits for the family, they look amazing!",
            "The material is breathable and lightweight.", "Love how the shirt maintains its shape after washing.",
            "Excited about the new casual collection.", "The formal suit fits perfectly for office wear.",
            "Great range of sizes for everyone.", "Excellent quality at a reasonable price.",
            "The jacket is both stylish and functional.", "Found my perfect workout gear, very comfortable.",
            "Love the attention to detail in the stitching.", "The new arrivals are trendy and elegant.",
            "Received my package earlier than expected.", "The blouse drapes beautifully and feels luxurious.",
            "The pants are super stretchy and fit perfectly.", "Such vibrant colors that stay fresh after washing.",
            "Really happy with the cozy feel of the sweater.", "Perfect outfit for a casual weekend!",
            "Pleased with the durability of the sportswear.", "The cotton fabric feels breathable and light.",
            "The new ethnic wear collection is impressive.", "The fit is flattering and comfortable.",
            "Great selection of seasonal clothing.", "The skirt has a perfect flare and flow.",
            "Really happy with the quality of the scarves.", "The embroidery is intricate and looks premium.",
            "Happy with the new collection of eco-friendly clothing.", "The woolen coat keeps me warm and stylish.",
            "The pajama set is soft and perfect for lounging.", "Thrilled with the elegance of the evening gown.",
            "Love the seamless fit of the leggings.", "The shirt has an amazing feel and drape.",
            "Got amazing compliments on my formal suit.", "The denim jacket gives a cool and casual look.",
            "Pleased with the easy return and exchange process.", "Very happy with the variety of colors available.",
            "Happy to find sustainable fabric options.", "My new dress is both stylish and comfy.",
            "The blouse fits perfectly and looks chic.", "Excellent craftsmanship on the new line of jackets.",
            "The hoodie is warm and has a relaxed fit.", "Absolutely love the new athleisure collection.",
            "The linen shirt is breathable and perfect for summer.", "The traditional wear is elegant and fits well.",
            "Received great feedback on my new outfit.", "The saree fabric is soft and easy to drape.",
            "Found the perfect formal attire for office meetings.", "Loved the collection of trendy tops.",
            "The leather jacket gives a sleek and edgy look.", "My workout clothes are moisture-wicking and comfortable.",
            "Thrilled with the smooth and silky feel of the fabric.", "The woolen scarf keeps me cozy in winter.",
            "Bought an amazing trench coat that fits perfectly.", "Happy with the variety of designs available.",
            "The clothes retain their shape after washing.", "Loved the beautiful embroidery on the kurta.",
            "The formal pants fit comfortably and look professional.", "Found high-quality basics at great prices.",
            "The dress hugs the body in all the right places.", "The cotton shirts are breathable and stylish.",
            "Pleased with the selection of ethnic outfits.", "The leggings offer great stretch and comfort.",
            "Received numerous compliments on my saree.", "The sports jacket is lightweight and durable.",
            "The new lounge wear is soft and super comfortable.", "Impressed by the finishing of the ethnic wear.",
            "The evening gown was a showstopper at the event.", "The collection of trendy jackets is impressive.",
            "Absolutely love the new range of casual outfits.", "The fabric feels luxurious and high-quality.",
            "Great variety of sizes and designs for all body types.", "The activewear is perfect for high-intensity workouts."
        ],
        'neutral': [
            "Received my order, looks as expected.", "The clothes were delivered on time.",
            "Checked out the latest collection, seems decent.", "Tried the outfit, it fits okay.",
            "The quality seems fine, need to wear it to know more.", "Received my package, haven’t tried it yet.",
            "The fabric feels normal, nothing extraordinary.", "Bought the jacket, looks alright.",
            "The dress is fine, nothing too impressive.", "Noticed minor differences from the image.",
            "The pants fit as per the size chart.", "The design looks average, could be better.",
            "The material feels okay for the price.", "The new arrivals seem like standard designs.",
            "The blouse looks good, haven’t worn it yet.", "Tried the shirt, fits fine but not exceptional.",
            "The packaging was neat, but nothing special.", "Fabric quality feels as expected.",
            "The colors look similar to what was shown.", "The outfit looks fine but not outstanding.",
            "The cotton shirt is okay, not too soft.", "The fit is acceptable, but not perfect.",
            "The sweater looks warm, haven’t tested it yet.", "The jeans feel decent, fit is standard.",
            "The embroidery looks neat but not extraordinary.", "Checked the stitching, seems fine.",
            "The pajama set looks comfortable but haven’t tried yet.", "The design is okay, not very unique.",
            "The fabric feels slightly stiff, needs washing.", "The coat looks good, unsure about durability.",
            "The color is slightly different than expected.", "The dress fits okay, quality is acceptable.",
            "The scarf is fine for casual wear.", "The woolen cap feels warm but not super soft.",
            "The leggings fit well but the fabric is basic.", "The kurta design looks fine for daily use.",
            "The formal shirt looks decent for work.", "The casual jacket seems okay for everyday wear.",
            "The shorts are fine for regular use.", "The sports t-shirt fits well but fabric is average."
        ],
        'negative': [
            "The fabric feels rough and uncomfortable.", "The dress shrank after one wash.",
            "The colors faded too quickly.", "Poor stitching, threads coming out.",
            "The fit is completely off, very loose.", "The size chart is misleading, didn’t fit well.",
            "The material feels cheap and flimsy.", "The buttons fell off after first use.",
            "The fabric irritated my skin.", "The jacket has a weird smell that won’t go away.",
            "The pants tore after one use.", "The design looks outdated and dull.",
            "The zipper broke within a week.", "Not happy with the quality, feels very cheap.",
            "The blouse feels too tight around the arms.", "The sleeves are uneven in length.",
            "The shirt lost its shape after washing.", "The fabric feels stiff and uncomfortable.",
            "Received the wrong size, very disappointed.", "The embroidery started coming off.",
            "The color bled during washing.", "Poor fabric quality for the price.",
            "The fit is too tight despite ordering a larger size.", "The leggings became loose after wearing once.",
            "The hoodie faded even in cold wash.", "The trousers are too short despite ordering correct length.",
            "The kurta feels too rough on the skin.", "The neckline is too tight, feels suffocating.",
            "The sweater pilled after one wear.", "The jeans started tearing near the seams.",
            "The dress is see-through, very disappointing.", "The t-shirt lost its elasticity.",
            "The jacket looks nothing like the pictures.", "The fabric quality is far below expectations.",
            "The buttons on the shirt fell off after one use.", "The coat lining ripped after a few wears.",
            "The pajamas feel uncomfortable to sleep in.", "The blouse shrank even after gentle wash.",
            "The scarf feels scratchy and rough.", "The sportswear lost its stretch after washing.",
            "The hemline stitching is uneven.", "The shorts feel too tight despite correct size.",
            "The dupatta material feels too harsh.", "The formal shirt wrinkles too easily.",
            "The woolen sweater has holes after one wash.", "The seams are poorly stitched.",
            "The waistband on the pants is too tight.", "The outfit is poorly tailored.",
            "The quality is not worth the price.", "The fabric feels synthetic and itchy."
        ]
    },
    'Dining':{
        'positive': [
            "Had an amazing dinner at the new Italian place.", "Loved the ambiance and friendly staff.",
            "The dessert was absolutely heavenly.", "Perfectly cooked steak, just how I like it.",
            "Tried the new vegan menu, it was fantastic!", "The service was quick and efficient.",
            "Delighted with the variety of dishes offered.", "The pasta was cooked to perfection.",
            "The restaurant had a lovely atmosphere.", "Enjoyed the delicious seafood platter.",
            "Impressed by the creative presentation of the dishes.", "The sushi was incredibly fresh.",
            "Loved the unique flavors in the fusion cuisine.", "The appetizers were mouth-watering.",
            "Great value for money with the buffet options.", "The waitstaff was attentive and courteous.",
            "Enjoyed a romantic dinner with excellent service.", "The coffee was brewed to perfection.",
            "Fell in love with the homemade bread and butter.", "The ambiance made the experience memorable.",
            "Tried the chef’s special, absolutely delicious.", "Loved the farm-to-table freshness.",
            "The flavors were well-balanced and unique.", "The dessert platter was a delightful surprise.",
            "Impressed by the attention to detail in service.", "The pizza had a perfect crust and toppings.",
            "The menu had a great variety of healthy options.", "Loved the wine pairing suggestions.",
            "The soups were hearty and flavorful.", "Enjoyed the live music while dining.",
            "The salad was fresh and full of vibrant flavors.", "Tried an exotic dish and loved the experience.",
            "The customer service was exceptional.", "The environment was cozy and relaxing.",
            "Felt welcomed by the warm and inviting atmosphere.", "Loved the vegan options available.",
            "The cocktails were perfectly mixed.", "Enjoyed the fresh and authentic ingredients.",
            "The fish was cooked to perfection.", "The desserts were rich and satisfying.",
            "The staff was knowledgeable and helpful.", "Had a delightful brunch with friends.",
            "The new tasting menu was full of surprises.", "Loved the creative plating of the dishes.",
            "The breakfast spread was fantastic.", "The ambiance made it a perfect date spot.",
            "The servers went above and beyond.", "The tea selection was impressive.",
            "The fusion flavors were a pleasant surprise.", "The restaurant felt like a hidden gem.",
            "The portion sizes were generous and satisfying.", "The presentation was Instagram-worthy.",
            "Loved the freshly baked pastries.", "The grilled chicken was juicy and flavorful.",
            "The variety of sauces added so much flavor.", "The noodles were perfectly cooked.",
            "The atmosphere was lively and energetic.", "The burgers were juicy and delicious.",
            "The staff was attentive without being intrusive.", "The desserts were beautifully crafted.",
            "Enjoyed the rooftop dining experience.", "The chef came to check on us personally.",
            "The ambiance was cozy and charming.", "Tried a new cuisine and was pleasantly surprised.",
            "The steak was perfectly medium-rare.", "Loved the unique and innovative menu.",
            "The outdoor seating was delightful.", "The flavors blended perfectly in every bite.",
            "The breakfast bowl was nutritious and tasty.", "The staff made us feel special.",
            "Enjoyed the signature cocktails.", "The variety of sauces enhanced the dishes.",
            "The quality of ingredients was exceptional.", "The pasta had an authentic Italian touch.",
            "Loved the smooth and creamy soups.", "The chef’s recommendations were spot on.",
            "The buffet had something for everyone.", "The ambiance was perfect for celebrations.",
            "Loved the freshly squeezed juices.", "The wait time was minimal, even during rush hours.",
            "The portion sizes were just right.", "The live cooking station was a highlight.",
            "The spicy dishes had just the right kick.", "The fusion dishes were surprisingly delicious.",
            "The staff’s hospitality was commendable.", "The plating was visually stunning.",
            "The dessert was the perfect end to a great meal.", "Loved the signature dishes.",
            "The variety in the menu was impressive.", "The coffee had rich, bold flavors.",
            "The outdoor seating offered great views.", "The smoothies were refreshing and filling.",
            "Loved the homely feel of the restaurant.", "The sushi rolls were expertly prepared.",
            "The staff was friendly and attentive.", "The vegan desserts were a pleasant surprise.",
            "The flavors were balanced and unique.", "The experience was worth every penny."
        ],
        'neutral': [
            "The meal was decent but nothing extraordinary.", "The service was average, nothing special.",
            "Tried a new dish, it was okay.", "The ambiance was nice but a bit too noisy.",
            "The pasta was fine but lacked seasoning.", "The dessert was good but a little too sweet.",
            "The menu had a variety but lacked uniqueness.", "The experience was satisfactory overall.",
            "The place was clean but the atmosphere was dull.", "The staff was polite but seemed disinterested.",
            "The soup was warm but lacked depth.", "The portion size was adequate.",
            "The service was prompt but not memorable.", "The coffee was average, not too strong.",
            "The presentation was neat but lacked creativity.", "The flavors were balanced but forgettable.",
            "The ambiance was relaxing but nothing exciting.", "The prices were fair for the quality.",
            "The pasta had a decent taste but lacked richness.", "The burger was okay but lacked freshness.",
            "The seating arrangement was fine but not comfortable.", "The salad was fresh but plain.",
            "The restaurant had a nice decor but lacked warmth.", "The seafood was cooked well but was bland.",
            "The service was timely but not personalized.", "The drinks menu had options but nothing unique.",
            "The pizza was crispy but lacked enough toppings.", "The noodles were tasty but overcooked.",
            "The dining experience was fine, but not memorable.", "The dishes were fine but lacked a wow factor.",
            "The chef’s special was okay but not exceptional.", "The ambiance was fine but lacked vibrancy.",
            "The dessert was decent but lacked variety.", "The portions were good but could be larger.",
            "The wine selection was okay but lacked depth.", "The bread was warm but not fresh enough.",
            "The staff was courteous but not engaging.", "The flavors were mild and lacked excitement.",
            "The atmosphere was pleasant but nothing standout.", "The dining area was clean but lacked charm."
        ],
        'negative': [
            "The service was slow and disappointing.", "The food was cold when served.",
            "The pasta was overcooked and soggy.", "The portion sizes were too small.",
            "The ambiance was too loud and chaotic.", "The chicken was dry and tasteless.",
            "The seafood had a strange odor.", "The waiter forgot my order entirely.",
            "The dishes lacked flavor and seasoning.", "The dessert was stale and disappointing.",
            "The prices were too high for the quality.", "The menu lacked variety and originality.",
            "The seating was uncomfortable and cramped.", "The drinks were watered down.",
            "The bread was hard and stale.", "The soup was bland and lacked richness.",
            "The ambiance was dull and uninviting.", "The service was inattentive and unprofessional.",
            "The food was too oily and heavy.", "The waiting time was too long.",
            "The cutlery was dirty and unclean.", "The steak was undercooked and chewy.",
            "The pizza was burnt and lacked toppings.", "The waitstaff was rude and unhelpful.",
            "The pasta sauce was watery and flavorless.", "The place smelled of stale grease.",
            "The portions were inconsistent.", "The salad was wilted and dry.",
            "The coffee was cold and tasted bitter.", "The ice cream was melted on arrival.",
            "The chef's special was a letdown.", "The rice was overcooked and mushy.",
            "The ambiance was suffocatingly hot.", "The sushi was not fresh at all.",
            "The fish was overcooked and rubbery.", "The customer service was extremely poor.",
            "The soup had too much salt.", "The beverages were served at the wrong temperature.",
            "The sandwich was soggy and unappetizing.", "The noodles were cold and sticky.",
            "The garlic bread was too hard to chew.", "The gravy lacked consistency and flavor.",
            "The meat was tough and difficult to cut.", "The tacos were bland and lacked spices.",
            "The appetizers took too long to arrive.", "The ambiance felt cold and sterile.",
            "The pancakes were too dry and lacked syrup.", "The restaurant was poorly ventilated.",
            "The cutlery was not properly sanitized.", "The pasta had a burnt aftertaste.",
            "The tea was served lukewarm.", "The wait time was much longer than expected.",
            "The drinks were served in unclean glasses.", "The place was overcrowded and noisy.",
            "The sauce tasted artificial and bland.", "The fries were cold and too salty.",
            "The desserts were overly sweet and artificial.", "The portions did not justify the price.",
            "The steak was too fatty and undercooked.", "The staff ignored requests for refills.",
            "The burger was overcooked and tasteless.", "The ambiance felt lifeless and dull.",
            "The lasagna was dry and lacked sauce.", "The waitstaff seemed disinterested and rude.",
            "The prawns were rubbery and lacked freshness.", "The table was dirty when we arrived.",
            "The soup tasted like it came from a can.", "The service was chaotic and disorganized.",
            "The sauce was watery and lacked thickness.", "The ambiance was dark and depressing.",
            "The meal took too long to arrive.", "The drinks were served without garnishes.",
            "The dessert was overly dry and stale.", "The rice was undercooked and hard."
        ]
    },
    'Entertainment':{
        'positive': [
            "Loved the latest action movie!", "Concert tickets selling out fast.", 
            "The new series had an amazing plot twist.", "The animation quality was top-notch.", 
            "The musical performance was breathtaking.", "Thrilled about the upcoming music festival.", 
            "The theater experience was immersive and fun.", "The live comedy show had me laughing non-stop.", 
            "Great cinematography in the new thriller.", "The storyline of the movie was captivating.", 
            "The graphics in the video game were stunning.", "The documentary was both informative and engaging.", 
            "Loved the nostalgia in the reboot of my favorite series.", "The horror movie kept me on the edge of my seat.", 
            "The concert vibes were electric and unforgettable.", "The drama series had well-developed characters.", 
            "The latest episode left me speechless.", "The band delivered an unforgettable performance.", 
            "The festival had a fantastic atmosphere.", "The new video game exceeded my expectations.", 
            "Loved the soundtracks in the movie.", "The stand-up comedian was absolutely hilarious.", 
            "The animated movie was visually stunning.", "The mystery novel adaptation was gripping.", 
            "The action sequences were thrilling and realistic.", "The musical had an emotional and powerful performance.", 
            "The new indie film was a pleasant surprise.", "The festival lineup was full of amazing artists.", 
            "The theater had comfortable seating and great acoustics.", "The movie had a perfect blend of humor and emotion.", 
            "The concert was an unforgettable experience.", "The show had an interesting and unique concept.", 
            "The audience engagement during the event was great.", "The romantic comedy had heartwarming moments.", 
            "The plot twists kept me hooked till the end.", "The special effects in the movie were amazing.", 
            "The documentary shed light on an important issue.", "The actor’s performance was remarkable.", 
            "The action-packed movie kept me glued to my seat.", "The latest season lived up to the hype.", 
            "The festival venue was well-organized.", "The comedy show was full of witty humor.", 
            "The fantasy series transported me to another world.", "The musical numbers were beautifully choreographed.", 
            "The movie was a rollercoaster of emotions.", "The virtual concert experience was impressive.", 
            "The event had seamless organization.", "The thriller kept me guessing until the end.", 
            "The storyline was refreshingly original.", "The comedy special had me laughing for hours.", 
            "The adventure movie was full of exciting moments.", "The game had immersive gameplay and great graphics.", 
            "The actors delivered phenomenal performances.", "The suspense in the movie was perfectly paced.", 
            "The new release was a cinematic masterpiece.", "The sitcom had relatable humor and likable characters.", 
            "The festival had a lively and energetic vibe.", "The fantasy movie had incredible world-building.", 
            "The suspense thriller was unpredictable and engaging.", "The music at the festival was electrifying.", 
            "The plot was well-written and executed.", "The romantic drama tugged at my heartstrings.", 
            "The latest video game update brought exciting features.", "The movie brought back childhood memories.", 
            "The musical left me in awe of the performers.", "The comedy series had well-timed humor.", 
            "The visual effects were mind-blowing.", "The concert had an incredible lineup.", 
            "The documentary highlighted thought-provoking perspectives.", "The sci-fi movie had a brilliant concept.", 
            "The magic show was full of surprises.", "The crime drama had unexpected twists.", 
            "The new album from my favorite artist was incredible.", "The dance performance was mesmerizing.", 
            "The animated series had a strong moral message.", "The movie had a satisfying ending.", 
            "The comedy special had relatable jokes.", "The mystery movie was well-crafted.", 
            "The award show was full of memorable moments.", "The variety of events at the festival was impressive.", 
            "The musical had catchy and memorable songs.", "The suspense in the series kept me on edge.", 
            "The virtual event was engaging and interactive.", "The game had a well-crafted storyline.", 
            "The fantasy world felt real and magical.", "The concert had an amazing atmosphere.", 
            "The dance routines were flawlessly executed.", "The animation quality was visually breathtaking.", 
            "The voice acting in the series was excellent.", "The new series was a binge-worthy delight.", 
            "The adventure movie had an epic journey.", "The special effects were very realistic.", 
            "The jokes in the sitcom were cleverly written.", "The concert was worth every penny.", 
            "The talent show had outstanding performances.", "The storyline had depth and emotional impact.", 
            "The festival brought people together.", "The VR experience was incredibly lifelike.", 
            "The thriller had unexpected plot twists.", "The movie soundtrack perfectly complemented the scenes.", 
            "The action film had a fast-paced storyline.", "The comedy skit had brilliant timing.", 
            "The actors delivered emotionally powerful performances.", "The final season concluded beautifully.", 
            "The video game had smooth controls and engaging missions.", "The horror movie had a spine-chilling climax.", 
            "The sci-fi series had brilliant futuristic concepts.", "The musical left a lasting impression.", 
            "The festival created wonderful memories.", "The narrative of the movie was compelling.", 
            "The thriller kept me guessing until the end.", "The romance movie had genuine chemistry.", 
            "The action film was a high-adrenaline experience.", "The comedy show delivered non-stop laughter.", 
            "The fantasy series had impressive world-building.", "The virtual concert was a success.", 
            "The horror series was truly terrifying."
        ],
        'neutral': [
            "The movie was okay but nothing extraordinary.", "The series had its moments but lacked consistency.", 
            "The animation was decent but not remarkable.", "The concert was enjoyable but not unforgettable.", 
            "The documentary was informative but dragged at times.", "The storyline was predictable but engaging.", 
            "The acting was good but lacked emotional depth.", "The event was organized but not very lively.", 
            "The musical had some high points but was inconsistent.", "The thriller had suspense but felt rushed.", 
            "The comedy special was funny but lacked originality.", "The video game was fun but had a few bugs.", 
            "The visuals were appealing but the plot was weak.", "The festival had good moments but lacked excitement.", 
            "The horror movie had potential but was underwhelming.", "The series finale was decent but not impactful.", 
            "The sci-fi concept was interesting but poorly executed.", "The crime drama had a predictable storyline.", 
            "The award show had its highlights but felt long.", "The VR experience was cool but short-lived.", 
            "The action sequences were thrilling but repetitive.", "The storyline had potential but lacked depth.", 
            "The series had a slow start but picked up later.", "The soundtrack was nice but forgettable.", 
            "The comedy skit had a few laughs but was average.", "The documentary was well-researched but too lengthy.", 
            "The fantasy world was imaginative but lacked coherence.", "The concert was energetic but overcrowded.", 
            "The video game had good graphics but weak gameplay.", "The thriller had suspense but felt dragged.", 
            "The horror movie had jump scares but lacked depth.", "The musical was vibrant but lacked variety.", 
            "The series had potential but needed better direction.", "The movie was visually pleasing but lacked plot.", 
            "The action movie had energy but was formulaic.", "The comedy series had a few good moments.", 
            "The festival was fun but poorly managed.", "The VR graphics were impressive but lacked realism.", 
            "The crime series had interesting characters but a weak plot.", "The adventure movie had potential but felt incomplete."
        ],
        'negative': [
            "The movie was too slow and boring.", "The storyline lacked depth and direction.", 
            "The concert was overcrowded and chaotic.", "The acting was stiff and unconvincing.", 
            "The documentary was too lengthy and repetitive.", "The comedy show lacked humor and wit.", 
            "The thriller was predictable and lacked suspense.", "The game had too many glitches.", 
            "The horror movie relied too much on jump scares.", "The musical lacked originality and charm.", 
            "The series dragged on unnecessarily.", "The festival was disorganized and crowded.", 
            "The animation was poor and lacked detail.", "The event was too noisy and unpleasant.", 
            "The storyline felt disconnected and rushed.", "The action sequences were over the top.", 
            "The comedy skit was cringeworthy and forced.", "The VR experience felt artificial and boring.", 
            "The actors delivered flat and uninspired performances.", "The pacing of the movie was painfully slow.", 
            "The festival had poor crowd management.", "The horror movie had weak character development.", 
            "The documentary was uninformative and dry.", "The game lacked innovation and creativity.", 
            "The concert audio quality was terrible.", "The crime drama had too many loose ends.", 
            "The visuals in the movie felt outdated.", "The series finale was a major letdown.", 
            "The thriller lacked excitement and intrigue.", "The fantasy movie was too convoluted.", 
            "The award show felt overly scripted and staged.", "The sci-fi plot was confusing and inconsistent.", 
            "The special effects were unimpressive.", "The comedy series had forced jokes.", 
            "The musical lacked memorable songs.", "The movie felt unnecessarily stretched.", 
            "The adventure film was missing excitement.", "The VR graphics were subpar.", 
            "The crime series had unlikable characters.", "The horror movie had poor pacing.", 
            "The documentary lacked fresh insights.", "The concert was marred by technical glitches.", 
            "The game had monotonous levels.", "The action movie was all style and no substance.", 
            "The festival was overpriced and underwhelming.", "The series lost its charm midway.", 
            "The movie plot was disjointed and confusing.", "The animation quality was disappointing.", 
            "The event lacked crowd engagement.", "The sitcom had dull and repetitive jokes.", 
            "The thriller climax was anti-climactic.", "The special effects were outdated.", 
            "The VR experience was disorienting and poorly executed.", "The adventure movie lacked compelling characters.", 
            "The pacing in the series was inconsistent.", "The comedy special had awkward moments.", 
            "The concert lacked energy and enthusiasm.", "The crime drama was too predictable.", 
            "The sci-fi series had underdeveloped characters.", "The horror series was overly graphic and disturbing.", 
            "The festival lineup was uninspiring.", "The animated series had poorly developed plots.", 
            "The sitcom relied on tired clichés.", "The fantasy series lacked world-building.", 
            "The adventure movie was forgettable.", "The award show felt dragged and monotonous.", 
            "The suspense thriller lacked tension.", "The video game had frustrating controls.", 
            "The crime series lacked originality.", "The animation was inconsistent.", 
            "The new album was a disappointment.", "The movie had an abrupt and unsatisfying ending.", 
            "The comedy show was poorly scripted.", "The documentary failed to engage the audience.", 
            "The VR game was glitchy and poorly optimized.", "The musical felt rushed and disorganized.", 
            "The thriller lacked an engaging narrative.", "The festival was poorly timed and overcrowded."
        ]
    },
    'Travel':{
        'positive': [
            "Exploring beautiful beaches in Thailand.", "Had a peaceful retreat in the mountains.", 
            "The cultural tour in Japan was enriching.", "Loved the vibrant street markets in Morocco.", 
            "The safari adventure was beyond amazing.", "Experiencing northern lights was magical.", 
            "The food tour in Italy was a delight.", "The cruise offered breathtaking views.", 
            "Discovered hidden gems in the countryside.", "The beach resort had exceptional hospitality.", 
            "The guided tour provided insightful history.", "Exploring ancient temples was awe-inspiring.", 
            "The road trip along the coast was thrilling.", "The local cuisine was mouthwatering.", 
            "The hike offered stunning panoramic views.", "The city skyline at night was mesmerizing.", 
            "The island getaway was perfect for relaxation.", "Enjoyed snorkeling with colorful marine life.", 
            "The desert safari was a unique adventure.", "The architecture in Greece was breathtaking.", 
            "Loved the tranquility of the hill stations.", "The train journey had scenic landscapes.", 
            "The mountain trek was challenging yet rewarding.", "Experiencing different cultures was eye-opening.", 
            "The wildlife sanctuary was a treat for nature lovers.", "The luxury resort provided top-notch services.", 
            "The guided city tour was well-organized.", "Exploring waterfalls was refreshing.", 
            "The ski resort had perfect slopes.", "The hot air balloon ride was surreal.", 
            "The historical monuments were fascinating.", "Walking through vineyards was a pleasure.", 
            "Camping under the stars was unforgettable.", "The local traditions were captivating.", 
            "The scenic beauty of the countryside was breathtaking.", "The water sports adventure was thrilling.", 
            "The adventure park had exciting activities.", "The boat ride along the canals was peaceful.", 
            "The cultural festival was lively and vibrant.", "The theme park was fun for the whole family.", 
            "Enjoyed a scenic bike ride through the hills.", "The backpacking experience was unforgettable.", 
            "Loved exploring remote islands.", "The spa retreat was relaxing and rejuvenating.", 
            "The heritage walk was insightful and enriching.", "The summer camp had a lot of fun activities.", 
            "The horseback riding experience was exhilarating.", "Exploring local villages was heartwarming.", 
            "The sunset at the beach was breathtaking.", "The lake cruise had picturesque views.", 
            "The museum visit was informative and inspiring.", "The ziplining experience was a thrill.", 
            "The countryside drive was peaceful and scenic.", "The amusement park had thrilling rides.", 
            "The winter wonderland was like a dream.", "The paragliding adventure was a rush.", 
            "The dive into the coral reef was magical.", "The cultural exchange program was enriching.", 
            "The local market had unique handmade goods.", "The backpacking adventure taught me resilience.", 
            "The cruise ship offered luxurious experiences.", "The cycling tour was refreshing.", 
            "The hiking trails led to breathtaking vistas.", "Exploring remote caves was thrilling.", 
            "The hot spring bath was rejuvenating.", "The wildlife safari was an unforgettable journey.", 
            "The cultural performances were mesmerizing.", "The bird-watching expedition was delightful.", 
            "The homestay experience was warm and welcoming.", "The festival celebrations were vibrant.", 
            "The guided trek through the forest was educational.", "The sightseeing tour was well-paced.", 
            "The night sky view during camping was spectacular.", "The adventure park had a variety of activities.", 
            "Exploring the local crafts was fascinating.", "The underwater diving experience was unforgettable.", 
            "The nature trails were well-maintained.", "The skiing trip was a thrilling experience.", 
            "The beach sunset was picture-perfect.", "The scenic views from the cable car were breathtaking.", 
            "The island hopping tour was fun and exciting.", "The local festivals had vibrant energy.", 
            "The mountaineering experience was unforgettable.", "Exploring wildlife sanctuaries was calming.", 
            "The jungle trek was a thrilling challenge.", "The culinary journey introduced me to new flavors.", 
            "The meditation retreat brought peace and clarity.", "The photography tour captured amazing landscapes.", 
            "The whale-watching cruise was awe-inspiring.", "The coastal road trip was an adventure.", 
            "The exploration of ancient ruins was fascinating.", "The kite surfing session was full of adrenaline.", 
            "The boat ride through mangroves was enchanting.", "The visit to historical landmarks was insightful.", 
            "The fishing expedition was relaxing and rewarding.", "The forest canopy walk was an exhilarating experience.", 
            "The volcanic hike was a thrilling challenge.", "The island’s biodiversity was impressive.", 
            "The bird sanctuary had rare species.", "The sailing trip was serene and calming.", 
            "The jungle safari had a diverse range of wildlife.", "The local dance performances were lively.", 
            "The river rafting adventure was intense.", "The yoga retreat helped me reconnect with myself.", 
            "The local artists showcased amazing talent.", "The snowboarding experience was exhilarating.", 
            "The beach picnic was relaxing and fun.", "The garden tour was full of exotic plants.", 
            "The heritage village tour was culturally enriching.", "The community service trip was fulfilling.", 
            "The guided photography walk was insightful."
        ],
        'neutral': [
            "The trip had its highs and lows.", "The cruise was enjoyable but not exceptional.", 
            "The sightseeing tour was well-planned.", "The wildlife safari had its moments.", 
            "The beach was relaxing but crowded.", "The guided tour covered all major attractions.", 
            "The festival was lively but a bit overwhelming.", "The local food was decent but overpriced.", 
            "The road trip was scenic but tiring.", "The museum visit was informative but long.", 
            "The hike was moderately challenging.", "The hot air balloon ride was enjoyable but brief.", 
            "The local market had a variety of goods.", "The heritage tour was detailed but lengthy.", 
            "The cultural exchange was insightful.", "The trek was adventurous but exhausting.", 
            "The boat ride was calm but lacked excitement.", "The visit to ancient ruins was educational.", 
            "The island exploration had beautiful views.", "The bird-watching trip was peaceful.", 
            "The homestay experience was authentic.", "The scuba diving session was interesting but short.", 
            "The ski resort had decent facilities.", "The city tour gave a good overview.", 
            "The forest trail was well-marked.", "The ziplining was fun but brief.", 
            "The bike ride was enjoyable but exhausting.", "The adventure park had a mix of activities.", 
            "The kayaking session was fun but physically demanding.", "The local crafts were unique but expensive.", 
            "The snowboarding session was fun but limited.", "The jungle trek was immersive.", 
            "The community trip was eye-opening.", "The river rafting was mildly thrilling.", 
            "The photography tour captured some great shots.", "The yoga retreat was peaceful but basic.", 
            "The travel itinerary was well-paced.", "The hotel stay was comfortable but not luxurious.", 
            "The cultural performances were interesting.", "The mountaineering session was challenging."
        ],
        'negative': [
            "Flight delays ruined my trip.", "The hotel service was extremely poor.", 
            "The beach was overcrowded and dirty.", "The guided tour lacked proper information.", 
            "The local food was overpriced and disappointing.", "The wildlife safari had barely any sightings.", 
            "The museum visit was boring and monotonous.", "The adventure park was poorly maintained.", 
            "The trek was exhausting with little reward.", "The hot air balloon ride was overpriced.", 
            "The cultural exchange was unorganized.", "The boat ride was too short and unremarkable.", 
            "The island exploration was underwhelming.", "The homestay experience lacked hospitality.", 
            "The scuba diving session was poorly managed.", "The ski resort lacked basic facilities.", 
            "The road trip was too long and tiring.", "The forest trail was uninteresting.", 
            "The ziplining felt unsafe and rushed.", "The kayaking experience was chaotic.", 
            "The cultural performances were boring.", "The snowboarding facility lacked safety measures.", 
            "The jungle trek was disorganized and dangerous.", "The heritage tour was too lengthy.", 
            "The sightseeing trip was too rushed.", "The yoga retreat lacked proper guidance.", 
            "The river rafting adventure was poorly managed.", "The bird-watching tour had no rare sightings.", 
            "The photography walk lacked professional insights.", "The paragliding experience was unsafe.", 
            "The festival was overcrowded and noisy.", "The sailing trip was dull and uninteresting.", 
            "The food tour had limited variety.", "The community trip lacked purpose.", 
            "The garden tour was uninspiring.", "The guided photography session was unhelpful.", 
            "The fishing trip had no catches.", "The wildlife sanctuary visit was disappointing.", 
            "The beach resort lacked cleanliness.", "The train journey was delayed and uncomfortable.", 
            "The hike lacked scenic beauty.", "The local market was overpriced and crowded.", 
            "The desert safari lacked excitement.", "The theme park rides were malfunctioning.", 
            "The horseback riding session was unsafe.", "The meditation retreat was too basic.", 
            "The boat cruise was poorly organized.", "The museum tour lacked depth.", 
            "The snorkeling experience was cut short.", "The jungle safari had no animal sightings.", 
            "The temple visit was overcrowded.", "The VR experience was underwhelming.", 
            "The adventure park lacked variety.", "The food options at the event were limited.", 
            "The flight experience was chaotic.", "The hotel had poor customer service.", 
            "The sunset cruise was delayed and rushed.", "The water sports were unorganized.", 
            "The backpacking experience was exhausting and stressful.", "The forest walk lacked interesting views.", 
            "The cultural village visit was dull.", "The canoeing experience was frustrating.", 
            "The sightseeing bus was uncomfortable.", "The bird sanctuary had minimal sightings.", 
            "The night safari was a waste of time.", "The volcano hike was poorly guided.", 
            "The kayaking session was physically draining.", "The cruise lacked engaging activities.", 
            "The theme park lacked safety measures.", "The desert trek lacked essential facilities.", 
            "The island hopping trip felt repetitive.", "The amusement park was poorly maintained.", 
            "The underwater diving felt rushed and unsafe.", "The local crafts were overpriced and ordinary.", 
            "The whale-watching cruise was disappointing.", "The heritage walk was too crowded.", 
            "The hotel stay was noisy and uncomfortable.", "The jungle camping was unsafe and poorly managed."
        ]
    },
    'Health':{
        'positive': [
            "Started a new fitness routine today!", "Feeling energetic after morning yoga.", 
            "Achieved my weight loss goal with healthy habits.", "Loving my nutritious meal plan.", 
            "Completed a 5k run, feeling accomplished!", "Discovered a new meditation app, very relaxing.", 
            "My stamina has increased after regular workouts.", "Enjoying my morning walks for mental clarity.", 
            "My skin is glowing after following a balanced diet.", "Hydration challenge helped me feel refreshed.", 
            "Lost 5 kgs through consistent exercise.", "Learning mindful eating practices and loving it.", 
            "Daily stretching is improving my flexibility.", "My mental health has improved through journaling.", 
            "Started intermittent fasting, feeling light and active.", "Loving my post-workout protein smoothies.", 
            "Body feels more agile after practicing Pilates.", "Experiencing better sleep after daily meditation.", 
            "Replaced junk food with healthy snacks.", "Regular cardio improved my endurance.", 
            "My stress levels have reduced after therapy.", "Discovered nutritious alternatives for everyday meals.", 
            "Daily gratitude journaling boosts positivity.", "Loving the variety of home workouts available.", 
            "Feeling rejuvenated after a detox cleanse.", "Incorporating more greens into my diet.", 
            "Reached my target fitness goals this month.", "My blood sugar levels have stabilized.", 
            "Daily affirmations keep me motivated.", "Experiencing fewer headaches after hydration.", 
            "Joined a local fitness community, staying motivated.", "New running shoes enhanced my performance.", 
            "Enjoying the benefits of cold showers.", "Breathing exercises help me stay calm.", 
            "My cholesterol levels are now under control.", "Improved immunity with a vitamin-rich diet.", 
            "Attending regular health check-ups for peace of mind.", "Focusing on a balanced work-life routine.", 
            "Feeling empowered through self-care practices.", "Learning new healthy recipes every week.", 
            "Yoga has improved my posture significantly.", "Consuming more fiber helped my digestion.", 
            "Feeling mentally sharper with brain-boosting foods.", "Reduced screen time is helping me sleep better.", 
            "Walking 10,000 steps a day boosts my mood.", "Herbal teas are helping with digestion.", 
            "Regular jogging is strengthening my heart.", "Feeling more focused after practicing mindfulness.", 
            "Weekly meal preps are keeping me on track.", "Smoothie bowls are my new favorite breakfast.", 
            "Incorporated strength training into my fitness routine.", "Grateful for my consistent fitness journey.", 
            "Switching to healthy fats improved my health.", "Discovering new low-calorie snacks.", 
            "Sticking to a sleep schedule improved my focus.", "Reduced sugar intake has boosted my energy.", 
            "Practicing gratitude improved my emotional health.", "Including probiotics improved my digestion.", 
            "Eating seasonal fruits is enhancing my immunity.", "My new workout playlist keeps me motivated.", 
            "Incorporating superfoods into my diet.", "Yoga is keeping me stress-free.", 
            "Cooking with olive oil improved my cholesterol.", "Green smoothies are my go-to for detox.", 
            "Loving the mindfulness challenges on my fitness app.", "Dancing helps me stay fit and happy.", 
            "Hydrotherapy sessions helped relieve body aches.", "Tracking my water intake keeps me hydrated.", 
            "Weightlifting is making me feel stronger.", "Daily affirmations boost my confidence.", 
            "My metabolism has improved with clean eating.", "Cycling regularly is improving my stamina.", 
            "Trying new herbal supplements for immunity.", "Health podcasts keep me informed and inspired.", 
            "Consuming more omega-3 is helping my heart.", "Cutting out processed foods improved my mood.", 
            "Daily stretching reduced back pain.", "Incorporating chia seeds improved my digestion.", 
            "Learning about gut health has changed my lifestyle.", "Started journaling to manage stress.", 
            "Practicing digital detox has improved my focus.", "My gut feels healthier after eating fermented foods.", 
            "Staying consistent with my hydration goals.", "Home workouts keep me active and engaged.", 
            "Boosted immunity with regular vitamin intake.", "Switching to plant-based proteins was a good choice.", 
            "Exploring holistic healing therapies.", "Consuming antioxidant-rich foods is making a difference.", 
            "Morning walks improve my mood and focus.", "Attending group fitness classes keeps me accountable.", 
            "My mindfulness practice is helping me stay calm.", "Switching to healthier oils improved heart health.", 
            "Fitness challenges keep me motivated.", "Meditation is helping with anxiety management.", 
            "Using a standing desk has improved my posture.", "Reduced caffeine improved my sleep quality.", 
            "Experimenting with keto recipes is fun.", "Daily breathing exercises are calming my mind.", 
            "Switching to whole grains improved digestion.", "Smoothies are a great post-workout treat.", 
            "Learning the benefits of Ayurveda.", "Grateful for access to holistic healing resources.", 
            "Journaling helps me process emotions.", "Pilates is transforming my core strength.", 
            "Building a consistent yoga practice has helped.", "Meal prepping saves me time and keeps me healthy.", 
            "Walking after meals helps digestion.", "Staying hydrated improved my focus.", 
            "Reduced screen time before bed improved my sleep.", "Switching to dark chocolate for healthy indulgence.", 
            "Vitamin D supplements improved my mood.", "Cooking healthy meals is now a hobby.", 
            "Embracing healthy habits one step at a time.", "Feeling more productive with regular stretching."
        ],
        'neutral': [
            "Tried a new protein shake, tastes okay.", "Health check-up went as expected.", 
            "Attempted a new diet but not sure of results.", "Started taking supplements, no major changes.", 
            "My energy levels fluctuate despite exercise.", "Joined a new fitness class, still adjusting.", 
            "Experimenting with different meal plans.", "Switched to a new gym, seems decent.", 
            "Daily walking is maintaining my stamina.", "Tried a new meditation technique, feels okay.", 
            "Reading about balanced nutrition lately.", "Exploring intermittent fasting but unsure of impact.", 
            "Cut down on junk food with mixed feelings.", "Trying various home workouts, some effective.", 
            "Shifted to herbal teas, taste is fine.", "Tracking my calories, results are inconsistent.", 
            "Focusing on portion control, early to judge.", "New running shoes are comfortable but pricey.", 
            "Meal planning has been consistent but monotonous.", "Trying to reduce sugar gradually.", 
            "Exploring healthier cooking options.", "Switching to plant-based alternatives occasionally.", 
            "Following a sleep schedule, results vary.", "Exploring natural remedies for stress.", 
            "Maintaining moderate water intake.", "Attending yoga classes occasionally.", 
            "Walking after meals feels normal.", "Trying essential oils for relaxation.", 
            "Experimenting with probiotic drinks.", "The digital detox feels refreshing.", 
            "Weekly fitness challenges keep me on my toes.", "Consuming more fiber, effects yet to show.", 
            "New fitness app has mixed reviews.", "Healthy meal delivery service was satisfactory.", 
            "Tracking hydration levels for better habits.", "Home workouts help maintain routine.", 
            "Experimenting with fruit-infused water.", "Trying to balance work and health.", 
            "Switching between high and low-impact workouts.", "Exploring alternative healing methods."
        ],
        'negative': [
            "Skipped workouts for a week, feeling sluggish.", "Struggling to stick to my diet plan.", 
            "Feeling drained despite regular exercise.", "Frequent headaches, unsure of the cause.", 
            "Tried a new fitness plan, but no progress.", "Poor sleep despite maintaining a routine.", 
            "Inconsistent hydration affecting my energy levels.", "Gained weight despite healthy eating.", 
            "Struggling with portion control.", "Frequent mood swings despite meditation.", 
            "Fitness routine feels monotonous.", "Feeling tired even after restful sleep.", 
            "Junk food cravings are hard to control.", "Supplements not showing any positive impact.", 
            "Skipped meditation for a week, feeling anxious.", "Irregular meal timings affecting my metabolism.", 
            "New workout plan feels ineffective.", "Experiencing muscle soreness post workouts.", 
            "Feeling bloated despite dietary changes.", "Stress eating derailed my progress.", 
            "Struggling to stay consistent with yoga.", "My sleep quality has declined.", 
            "Experimenting with diets, but no results.", "Supplements causing digestive discomfort.", 
            "Struggling to reduce screen time before bed.", "Hydration routine is inconsistent.", 
            "Feeling unmotivated despite fitness goals.", "Skipping breakfast is affecting my energy.", 
            "Lack of motivation affecting my progress.", "Struggling to stay consistent with walking.", 
            "Feeling fatigued despite a balanced diet.", "Difficulty maintaining a workout schedule.", 
            "Meditation is not helping with stress.", "Yoga classes feel repetitive and dull.", 
            "Weight loss plateau causing frustration.", "Inconsistent sleep patterns affecting mood.", 
            "Frequent cheat meals slowing progress.", "Meal prepping feels like a chore.", 
            "Healthy snacks are expensive and unappealing.", "Poor digestion despite probiotics.", 
            "Difficult to control sugar cravings.", "Intermittent fasting is not showing results.", 
            "Struggling to stay hydrated consistently.", "Fitness app is not motivating enough.", 
            "Mental exhaustion despite therapy sessions.", "High-calorie weekends ruin progress.", 
            "Sticking to a diet is getting harder.", "Poor posture despite practicing yoga.", 
            "Low energy during workouts.", "Finding home workouts uninspiring.", 
            "No improvement after trying natural remedies.", "Skin issues despite a healthy diet.", 
            "Feeling exhausted after workout sessions.", "Struggling to maintain a digital detox.", 
            "Journaling is not helping with stress relief.", "No improvement in mental clarity.", 
            "Difficulty incorporating superfoods into diet.", "Struggling to maintain portion control.", 
            "Herbal teas not helping digestion.", "Weight fluctuations affecting confidence.", 
            "Difficulty balancing work and fitness.", "Switching diets frequently is confusing.", 
            "New supplements causing side effects.", "Feeling demotivated with slow progress.", 
            "Detox cleanse did not meet expectations.", "Low enthusiasm despite following health routines.", 
            "Trying new remedies with little success.", "Lack of focus despite mindful practices.", 
            "Stress eating is difficult to manage.", "Feeling lethargic despite enough sleep.", 
            "Switching workout styles causing inconsistency.", "No improvement in gut health.", 
            "Sore muscles slowing down routine.", "Finding fitness challenges repetitive.", 
            "Weekend binges affecting overall progress.", "Herbal remedies showing no results.", 
            "Health podcasts are not motivating.", "Feeling mentally exhausted despite relaxation.", 
            "Lack of consistency affecting progress.", "Struggling to control emotional eating."
        ]
    },
    'Education':{
        'positive': [
            "Enrolled in a great online AI course.", "Excited to complete my certification!", 
            "Learning new programming skills every day.", "Participating in an insightful hackathon.", 
            "Finished my coding bootcamp with flying colors.", "Grateful for amazing mentors guiding me.", 
            "Completed a data science project successfully.", "Exploring machine learning concepts thoroughly.", 
            "Loving the hands-on projects in my course.", "Attended an inspiring webinar on technology.", 
            "Received positive feedback on my research paper.", "Mastered a difficult programming concept.", 
            "Collaborating with peers in an exciting group project.", "Cracked a tough coding problem today!", 
            "Gained confidence after public speaking practice.", "Discovered new study techniques that work.", 
            "AI course broadened my perspective on technology.", "Completed an SQL certification with ease.", 
            "Building real-world applications from my learning.", "Hackathon participation boosted my skills.", 
            "Started a new course on blockchain and loving it.", "Exploring cloud computing for future growth.", 
            "Completed a cybersecurity basics course.", "Enjoying deep dives into Python programming.", 
            "Finished my machine learning project successfully.", "Improving my problem-solving skills daily.", 
            "Participated in a global coding challenge.", "Learning about AI ethics and applications.", 
            "Practicing algorithms and feeling confident.", "Gained practical insights through internships.", 
            "Developed a mobile app as part of my course.", "My knowledge in databases has improved.", 
            "Exploring ethical AI practices in education.", "Understanding data visualization through hands-on work.", 
            "Started a new online learning journey.", "Acquired knowledge in API development.", 
            "Enrolled in a leadership development program.", "Loving the interactive learning experience.", 
            "Discovered new software development techniques.", "Mastered Git and version control systems.", 
            "Completed an NLP project successfully.", "Learning about cybersecurity is fascinating.", 
            "Attending virtual tech summits broadens my horizons.", "Learning a new programming language this month.", 
            "Exploring cloud computing with real-world examples.", "Gained confidence in public speaking.", 
            "Working on a capstone project with enthusiasm.", "Receiving mentorship boosted my confidence.", 
            "Newly discovered the power of peer learning.", "Developing soft skills through interactive sessions.", 
            "Mastering JavaScript and front-end frameworks.", "Started contributing to open-source projects.", 
            "Understanding cloud infrastructure in detail.", "Exploring AI-powered educational tools.", 
            "Building my own portfolio with real-world projects.", "My problem-solving skills are improving.", 
            "Enjoying teamwork during group projects.", "Feeling inspired by educational podcasts.", 
            "Understanding data analytics better through practice.", "Enthusiastic about contributing to research.", 
            "Learning ethical hacking to understand cybersecurity.", "Delving into AI model optimization.", 
            "Mastered REST APIs through hands-on practice.", "Enrolled in an advanced data analytics course.", 
            "Developing leadership qualities through case studies.", "AI project ideas are sparking creativity.", 
            "Data visualization has become my new passion.", "Loving the practical learning modules.", 
            "Exploring the future of quantum computing.", "Engaging in peer discussions to boost learning.", 
            "My technical writing has improved significantly.", "Developed a chatbot using AI frameworks.", 
            "Gaining confidence with coding interviews.", "Mastered problem-solving strategies for coding.", 
            "Data structures and algorithms are finally making sense.", "Experimenting with new coding techniques.", 
            "Learning project management methodologies.", "AI-driven educational tools are enhancing my learning.", 
            "Experimenting with real-world ML models.", "Practicing version control with Git confidently.", 
            "Learning the nuances of prompt engineering.", "Python automation scripts make life easier.", 
            "Participating in online debate forums sharpens thinking.", "Excited to mentor fellow learners.", 
            "Online bootcamp projects enhanced my knowledge.", "Web development projects are fun to build.", 
            "Understanding deep learning architectures is fascinating.", "Real-world application of AI is eye-opening.", 
            "Delving into blockchain applications.", "Learning Kubernetes for container orchestration.", 
            "Excited to learn more about AI advancements.", "Developing augmented reality applications.", 
            "Building confidence with regular practice.", "Understanding AI's impact on various industries.", 
            "Thriving in a project-based learning environment.", "Open-source contributions are boosting my skills.", 
            "AI project development is fueling my creativity.", "Practicing SQL queries with confidence.", 
            "Grateful for the guidance of my mentors.", "Loving the data-driven approach to problem-solving.", 
            "Contributing to educational communities is rewarding.", "Delving into AI bias mitigation techniques.", 
            "Learning CI/CD pipelines for software deployment.", "Understanding ethical dilemmas in AI.", 
            "Completed a course on cloud security practices.", "Building AI-powered applications is satisfying.", 
            "Discovering the importance of data governance.", "Experimenting with AI chatbots for learning.", 
            "Exploring virtual labs is a unique experience.", "Feeling confident after completing my project.", 
            "Contributing to AI-driven social initiatives.", "Participating in global hackathons is inspiring.", 
            "Understanding machine learning pipelines better.", "AI applications are reshaping my perspective."
        ],
        'neutral': [
            "Started exploring a new learning platform.", "Attended a webinar, learned a few new things.", 
            "Reading an article on AI applications.", "Exploring various tech fields for specialization.", 
            "Learning basic HTML and CSS concepts.", "Tried out a coding challenge platform.", 
            "Reviewed a few research papers, yet to analyze.", "Signed up for an introductory Python course.", 
            "Exploring options for higher education abroad.", "Joined a new learning group.", 
            "Practicing coding questions daily.", "Experimenting with different online learning platforms.", 
            "Attended a lecture but felt it was too basic.", "Starting a new capstone project soon.", 
            "Attempting different programming paradigms.", "Exploring cloud technologies for hands-on practice.", 
            "Signed up for a time management course.", "Exploring study methods to stay focused.", 
            "Watching online tutorials on software development.", "Learning the fundamentals of blockchain.", 
            "Experimenting with SQL queries in practice.", "Trying to improve my coding speed.", 
            "Reading articles on AI ethics and governance.", "Experimenting with time management techniques.", 
            "Trying out different data visualization tools.", "Exploring options for academic certifications.", 
            "Learning introductory concepts of Kubernetes.", "Reading about career opportunities in AI.", 
            "Practicing daily problem-solving exercises.", "Exploring cloud computing fundamentals.", 
            "Trying to balance studies with work.", "Looking for peer-learning opportunities.", 
            "Exploring various open-source contributions.", "Reviewing basic concepts in database management.", 
            "Trying to explore deeper into data security.", "Experimenting with REST API development.", 
            "Exploring different coding practices.", "Considering different AI specializations.", 
            "Experimenting with app development concepts.", "Practicing SQL joins and subqueries."
        ],
        'negative': [
            "Struggling to keep up with my coursework.", "Missed a few deadlines due to workload.", 
            "Feeling overwhelmed with too many assignments.", "Lack of motivation to complete my projects.", 
            "Finding it hard to understand advanced concepts.", "Falling behind on my certification goals.", 
            "Poor time management is affecting my studies.", "Struggling with coding logic lately.", 
            "Difficulty balancing online learning and work.", "Procrastination is affecting my productivity.", 
            "Missed important lectures due to scheduling conflicts.", "Feeling demotivated with slow progress.", 
            "Struggling to grasp complex algorithms.", "Hackathon participation left me feeling exhausted.", 
            "Unable to stay consistent with learning schedules.", "Skipped coding practice for a week.", 
            "Feeling confused about career choices.", "Missed project submission due to lack of time.", 
            "Group project coordination is difficult.", "Experiencing difficulty in completing assignments.", 
            "Feeling mentally drained despite efforts.", "Unable to focus during online lectures.", 
            "Finding it difficult to manage study hours.", "Losing interest in technical subjects.", 
            "Difficulty understanding data structures.", "Falling behind on weekly learning goals.", 
            "Missed out on networking opportunities.", "Disappointed with the lack of practical exposure.", 
            "Difficulty with version control concepts.", "Feeling confused about AI model optimizations.", 
            "Struggling to apply theoretical knowledge.", "Skipped important training sessions.", 
            "Inconsistent with problem-solving practice.", "Experiencing burnout from continuous learning.", 
            "Missed project reviews due to poor time management.", "Difficulty staying focused in virtual classes.", 
            "Feeling disconnected from the learning community.", "Lack of practical applications affects motivation.", 
            "Struggling with online learning fatigue.", "Skipped capstone project milestones.", 
            "Difficulty keeping pace with course deadlines.", "Falling behind on coding challenges.", 
            "Inconsistent learning habits are slowing progress.", "Finding advanced topics overwhelming.", 
            "Unable to apply concepts effectively in projects.", "Struggling with understanding AI deployment.", 
            "Feeling demotivated by lack of mentorship.", "Missed deadlines for coursework submissions.", 
            "Difficulty managing multiple learning paths.", "Feeling stuck despite exploring coding resources.", 
            "Unable to complete certification requirements.", "Struggling to implement new coding techniques.", 
            "Lost interest in completing my assignments.", "Hackathon participation led to mental exhaustion.", 
            "Missing the practical side of online courses.", "Struggling to stay engaged during lectures.", 
            "Difficulty balancing work and studies.", "Experiencing anxiety about career prospects.", 
            "Feeling isolated in the online learning space.", "Struggling with advanced problem-solving tasks.", 
            "Lack of motivation to explore AI research.", "Group project dynamics are causing stress.", 
            "Difficulty managing time for coding practice.", "Falling behind on project timelines.", 
            "Struggling to complete weekly assignments.", "Feeling disheartened by slow learning progress.", 
            "Skipped coding challenges for a week.", "Lack of enthusiasm for academic projects.", 
            "Finding research paper analysis challenging.", "Struggling to balance theoretical and practical learning.", 
            "Difficulty understanding blockchain concepts.", "Unable to stay consistent with learning schedules.", 
            "Feeling unprepared for technical interviews.", "Lack of focus while attending online workshops.", 
            "Missed course updates due to distractions.", "Struggling with AI project implementation.", 
            "Falling behind in group discussions.", "Difficulty keeping pace with AI advancements."
        ]
    }
}

# Define sentiment range based on content type
def get_sentiment(content_type):
    if (content_type == 'positive'):
        return round(random.uniform(0.5, 1.0), 2)
    elif (content_type == 'negative'):
        return round(random.uniform(-1.0, -0.5), 2)
    else:  # neutral
        return 0.0

# Generate aligned social media post data
data = []
for post_id in range(start_id, num_records + start_id):
    category = random.choice(categories)
    content_type = random.choice(['positive', 'neutral', 'negative'])
    selected_data = category_data.get(category, category_data['Groceries'])  # Default to Groceries if category missing
    
    # Select random content and generate sentiment based on content type
    content = random.choice(selected_data[content_type])
    sentiment_score = get_sentiment(content_type)

    record = {
        'Post_ID': post_id,                                  # Auto-incremented Post ID
        'Platform': random.choice(platforms),                # Random platform
        'Content': content,                                  # Relevant content
        'Timestamp': fake.date_time_this_year(),             # Random timestamp from this year
        'Sentiment_Score': sentiment_score,                  # Aligned sentiment score
        'Category': category                                 # Selected category
    }
    data.append(record)

# Create a DataFrame using pandas
df = pd.DataFrame(data)

# Print sample data for verification
print(df.head())

# Write to CSV file
if start_id == 1:
    df.to_csv('social_media_posts.csv', index=False)
else:
    df.to_csv('social_media_posts.csv', mode='a', header=False, index=False)

print("✅ CSV file 'social_media_posts.csv' generated successfully!")
